# Generated by Django 3.2.8 on 2021-10-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_exammarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classrooms',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='parents',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'managed': True},
        ),
    ]
