# Generated by Django 3.2.8 on 2021-11-03 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211029_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='classroomid',
            field=models.ForeignKey(blank=True, db_column='ClassroomID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.classrooms'),
        ),
        migrations.AddField(
            model_name='students',
            name='parent',
            field=models.ForeignKey(db_column='Parent_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.parents'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.IntegerField(db_column='Student_ID', error_messages={'unique': 'The Student ID is already taken'}, primary_key=True, serialize=False, unique=True),
        ),
    ]
